module.exports = (config) => ({
  type: "widget",
  name: "PositionsWidget",
  bundleIdentifier: ".widget",
  deploymentTarget: "18.0",
  frameworks: ["SwiftUI", "WidgetKit", "AppIntents"],
  entitlements: {
    "com.apple.security.application-groups": ["group.com.depthly.app.shared"],
  },
  resources: [
    "../../assets/fonts/Satoshi-Regular.otf",
    "../../assets/fonts/Satoshi-Medium.otf",
    "../../assets/fonts/Satoshi-Bold.otf",
    "../../assets/fonts/Satoshi-Black.otf",
  ],
  colors: {
    "Background/Primary":   { light: "#FFFFFF", dark: "#000000" },
    "Background/Surface":   { light: "#F7F9F9", dark: "#16181C" },
    "Background/Variant":   { light: "#EFF3F4", dark: "#202327" },
    "Text/Primary":         { light: "#0F1419", dark: "#E7E9EA" },
    "Text/Muted":           { light: "#536471", dark: "#8B8F95" },
    "Border/Outline":       { light: "#B5BEC4", dark: "#4A4D52" },
    "Brand/Primary":        { light: "#CC0062", dark: "#FF007A" },
    "Brand/Glow":           { light: "#FF007A", dark: "#FF007A" },
    "Status/InRange":       { light: "#10B981", dark: "#00FFA1" },
    "Status/OutOfRange":    { light: "#F59E0B", dark: "#FFD60A" },
    "Status/Error":         { light: "#F4212E", dark: "#F4212E" },
    "Chains/Ethereum":      { light: "#627EEA", dark: "#627EEA" },
    "Chains/Base":          { light: "#0052FF", dark: "#0052FF" },
    "Chains/Arbitrum":      { light: "#28A0F0", dark: "#28A0F0" },
    "Chains/Optimism":      { light: "#FF0420", dark: "#FF0420" },
    "Chains/Polygon":       { light: "#8247E5", dark: "#8247E5" },
    "Chains/Bnb":           { light: "#F3BA2F", dark: "#F3BA2F" },
    "Chains/Avalanche":     { light: "#E84142", dark: "#E84142" },
  },
});
