export default {
  spacing: {
    none: { $value: 0 },
    xxs: { $value: 2 },
    xs: { $value: 4 },
    sm: { $value: 8 },
    md: { $value: 12 },
    lg: { $value: 16 },
    xl: { $value: 20 },
    "2xl": { $value: 24 },
    "3xl": { $value: 32 },
    "4xl": { $value: 40 },
    "5xl": { $value: 48 },
    "6xl": { $value: 64 },
    "7xl": { $value: 80 },
    "8xl": { $value: 96 },
  },
  radius: {
    none: { $value: 0 },
    xs: { $value: 4 },
    sm: { $value: 8 },
    md: { $value: 12 },
    lg: { $value: 16 },
    xl: { $value: 20 },
    "2xl": { $value: 24 },
    "3xl": { $value: 32 },
    full: { $value: 9999 },
  },
};
