import { tokenAlias } from "../../kit/alias";
import paletteTokens from "./palette";

const palette = tokenAlias(paletteTokens);

export default {
  color: {
    depthly: {
      $type: "color",
      dark: {
        primary: palette("color.palette.neonPink.500"),
        onPrimary: palette("color.palette.white"),
        primaryContainer: { $value: "#33001A" },
        onPrimaryContainer: palette("color.palette.neonPink.100"),
        secondary: palette("color.palette.neonPink.300"),
        onSecondary: { $value: "#0A0A0B" },
        secondaryContainer: { $value: "#330014" },
        onSecondaryContainer: palette("color.palette.neonPink.100"),
        surface: palette("color.palette.black"),
        onSurface: palette("color.palette.neutral.100"),
        // dim/bright are the page and the raised content it holds. The ramp runs in
        // opposite directions per theme, so each mode has one of the pair coincide with
        // an adjacent role — as in M3's own baseline. They are not aliases of it.
        surfaceDim: palette("color.palette.black"),
        surfaceBright: { $value: "#16181C" },
        surfaceContainer: { $value: "#16181C" },
        surfaceVariant: { $value: "#202327" },
        onSurfaceVariant: { $value: "#8B8F95" },
        outline: { $value: "#4A4D52" },
        outlineVariant: { $value: "#33363A" },
        error: palette("color.palette.red.500"),
        onError: palette("color.palette.white"),
        errorContainer: { $value: "#3A0A0E" },
        onErrorContainer: { $value: "#FFD6D9" },
        success: { $value: "#00FFA1" },
        onSuccess: { $value: "#001F0F" },
        warning: { $value: "#FFD60A" },
        onWarning: { $value: "#1A1500" },
        info: { $value: "#00D4FF" },
        onInfo: { $value: "#001A26" },
        inverseSurface: palette("color.palette.neutral.100"),
        inverseOnSurface: palette("color.palette.neutral.900"),
        inversePrimary: palette("color.palette.neonPink.700"),
        scrim: palette("color.palette.black"),
        shadow: palette("color.palette.neonPink.500"),
      },
      light: {
        primary: palette("color.palette.neonPink.700"),
        onPrimary: palette("color.palette.white"),
        primaryContainer: palette("color.palette.neonPink.100"),
        onPrimaryContainer: palette("color.palette.neonPink.900"),
        secondary: palette("color.palette.neonPink.500"),
        onSecondary: palette("color.palette.white"),
        secondaryContainer: { $value: "#FFEBF3" },
        onSecondaryContainer: palette("color.palette.neonPink.900"),
        surface: palette("color.palette.white"),
        onSurface: palette("color.palette.neutral.900"),
        surfaceDim: { $value: "#F7F9F9" },
        surfaceBright: palette("color.palette.white"),
        surfaceContainer: { $value: "#F7F9F9" },
        surfaceVariant: { $value: "#EFF3F4" },
        onSurfaceVariant: { $value: "#536471" },
        outline: { $value: "#B5BEC4" },
        outlineVariant: { $value: "#DFE4E7" },
        error: palette("color.palette.red.500"),
        onError: palette("color.palette.white"),
        errorContainer: { $value: "#FFE0E3" },
        onErrorContainer: { $value: "#5F0010" },
        success: { $value: "#10B981" },
        onSuccess: palette("color.palette.white"),
        warning: { $value: "#F59E0B" },
        onWarning: { $value: "#1A1500" },
        info: { $value: "#0EA5E9" },
        onInfo: palette("color.palette.white"),
        inverseSurface: palette("color.palette.neutral.900"),
        inverseOnSurface: palette("color.palette.neutral.100"),
        inversePrimary: palette("color.palette.neonPink.500"),
        scrim: palette("color.palette.black"),
        shadow: palette("color.palette.neonPink.500"),
      },
    },
  },
};
