export default {
  color: {
    depthly: {
      $type: "color",
      dark: {
        primary: { $value: "#FF007A" },
        onPrimary: { $value: "#FFFFFF" },
        primaryContainer: { $value: "#33001A" },
        onPrimaryContainer: { $value: "#FFD6E8" },
        secondary: { $value: "#FF80BE" },
        onSecondary: { $value: "#0A0A0B" },
        secondaryContainer: { $value: "#330014" },
        onSecondaryContainer: { $value: "#FFD6E8" },
        surface: { $value: "#000000" },
        onSurface: { $value: "#E7E9EA" },
        surfaceContainer: { $value: "#16181C" },
        surfaceVariant: { $value: "#202327" },
        onSurfaceVariant: { $value: "#8B8F95" },
        outline: { $value: "#4A4D52" },
        outlineVariant: { $value: "#33363A" },
        error: { $value: "#F4212E" },
        onError: { $value: "#FFFFFF" },
        errorContainer: { $value: "#3A0A0E" },
        onErrorContainer: { $value: "#FFD6D9" },
        success: { $value: "#00FFA1" },
        onSuccess: { $value: "#001F0F" },
        warning: { $value: "#FFD60A" },
        onWarning: { $value: "#1A1500" },
        inverseSurface: { $value: "#E7E9EA" },
        inverseOnSurface: { $value: "#0F1419" },
        inversePrimary: { $value: "#CC0062" },
        scrim: { $value: "#000000" },
        shadow: { $value: "#FF007A" },
      },
      light: {
        primary: { $value: "#CC0062" },
        onPrimary: { $value: "#FFFFFF" },
        primaryContainer: { $value: "#FFD6E8" },
        onPrimaryContainer: { $value: "#660031" },
        secondary: { $value: "#FF007A" },
        onSecondary: { $value: "#FFFFFF" },
        secondaryContainer: { $value: "#FFEBF3" },
        onSecondaryContainer: { $value: "#660031" },
        surface: { $value: "#FFFFFF" },
        onSurface: { $value: "#0F1419" },
        surfaceContainer: { $value: "#F7F9F9" },
        surfaceVariant: { $value: "#EFF3F4" },
        onSurfaceVariant: { $value: "#536471" },
        outline: { $value: "#B5BEC4" },
        outlineVariant: { $value: "#DFE4E7" },
        error: { $value: "#F4212E" },
        onError: { $value: "#FFFFFF" },
        errorContainer: { $value: "#FFE0E3" },
        onErrorContainer: { $value: "#5F0010" },
        success: { $value: "#10B981" },
        onSuccess: { $value: "#FFFFFF" },
        warning: { $value: "#F59E0B" },
        onWarning: { $value: "#1A1500" },
        inverseSurface: { $value: "#0F1419" },
        inverseOnSurface: { $value: "#E7E9EA" },
        inversePrimary: { $value: "#FF007A" },
        scrim: { $value: "#000000" },
        shadow: { $value: "#FF007A" },
      },
    },
  },
};
