import { depthlyDark, fontFamily, letterSpacing, lineHeight, networkColors, palette, radius, spacing, typography } from "@depthly/theme";

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "..", "src", "assets", "css", "tokens.css");

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const lines: string[] = [];
lines.push("/* Generated by scripts/build-tokens.ts from @depthly/theme — do not edit. */");
lines.push(":root {");

for (const [k, v] of Object.entries(depthlyDark)) {
  lines.push(`  --color-${kebab(k)}: ${v};`);
}

for (const [k, v] of Object.entries(palette)) {
  lines.push(`  --palette-${kebab(k)}: ${v};`);
}

for (const [chain, c] of Object.entries(networkColors)) {
  lines.push(`  --network-${chain}: ${c.base};`);
}

for (const [k, v] of Object.entries(spacing)) {
  lines.push(`  --space-${k}: ${v}px;`);
}

for (const [k, v] of Object.entries(radius)) {
  lines.push(`  --radius-${k}: ${v}px;`);
}

for (const [k, v] of Object.entries(fontFamily)) {
  lines.push(`  --font-family-${k}: ${v};`);
}

for (const [k, v] of Object.entries(lineHeight)) {
  lines.push(`  --line-height-${k}: ${v};`);
}

for (const [k, v] of Object.entries(letterSpacing)) {
  lines.push(`  --letter-spacing-${k}: ${v}px;`);
}

for (const [role, style] of Object.entries(typography)) {
  lines.push(`  --type-${role}-family: ${style.fontFamily};`);
  lines.push(`  --type-${role}-size: ${style.fontSize}px;`);
  lines.push(`  --type-${role}-weight: ${style.fontWeight};`);
  lines.push(`  --type-${role}-line-height: ${style.lineHeight}px;`);
  lines.push(`  --type-${role}-letter-spacing: ${style.letterSpacing}px;`);
}

lines.push("}");

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, `${lines.join("\n")}\n`, "utf8");

console.log(`tokens.css → ${outPath}`);
